In [1]:
import numpy as np

Task 1

In [11]:
def array_factory(mode , shape, value=None):
    """
        Creates various NumPy arrays based on the mode.
        - 'zeros': Array filled with 0.
        - 'ones': Array filled with 1.
        - 'full': Array filled with a specified 'value'.
        - 'identity': A square identity matrix of size 'shape'.
   """
    if mode=="zeros":
        return np.zeros(shape)
    
    elif mode=="ones":
        return np.ones(shape)
    elif mode=="full":
        return np.full(shape, value)
    elif mode=="identity":
        return np.identity(shape)
    else:
        raise ValueError("invalid mode")

In [12]:
array_factory("identity", 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Task 2

In [13]:
def secure_reshape_and_stack(data1, data2, new_shape):
    """
        1. Validates and converts inputs to NumPy arrays.
        2. Reshapes the first dataset to a specific dimension.
        3. Vertically stacks both datasets into one matrix.
    """
    
    try:
        #convert inputs to ndarray
        
        arr1 = np.array(data1)
        arr2 = np.array(data2)
        
        #reshape arr1 to new_shape
    
        reshaped_arr1 = arr1.reshape(new_shape)
        
        #vertical stacking
        
        combined_dataset = np.vstack((reshaped_arr1, arr2))
        
        return combined_dataset
    
    
    except ValueError as e:
        raise ValueError(f"company-grade Error:{e}")
    
    
    

In [15]:
data1 = [1, 2, 3, 4, 5, 6]
data2 = [[7, 8, 9]]
new_shape = (2, 3)
 
result = secure_reshape_and_stack(data1, data2, new_shape)

print(result) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
data1 = [1, 2, 3, 4, 5, 6]
data2 = [[7, 8]]
new_shape = (2, 3)

result = secure_reshape_and_stack(data1, data2, new_shape)
print(result) 

ValueError: company-grade Error:all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2