In [1]:
import numpy as np

In [16]:
v= np.array([1,2,3])
m= np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
s=np.array(5)
print(v.ndim)
print(m.ndim)
print(s.ndim)
print(v.shape)
print(m.shape)
print(s.shape)

1
2
0
(3,)
(3, 3)
()


In [10]:
class student:
    def __init__(self, name):
        self._name = name
        
    @property    
    def name(self):
        return self._name
    
    @name.setter
    def name(self, name):
        self._name = name
        

In [11]:
s1= student("sondos")
s1.name = "sara"

In [15]:
vec = np.array([1,2,3,4,5,6])
mat= vec.reshape((3,2))
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
vec= np.array([1,2,3,4])
mat= vec.reshape((vec.shape[0],1))
mat

array([[1],
       [2],
       [3],
       [4]])

In [24]:
vec= np.array([1,2,3,4])
mat= vec[: ,None]
mat

array([[1],
       [2],
       [3],
       [4]])

In [25]:
def array_reshape(arr, row: int = -1, col: int = -1):
    
    try:
        arr = np.array(arr)
        return arr.reshape((row, col))
    except (TypeError, ValueError) as e:
        raise ValueError(f"Invalid input: {e}")
   

In [28]:
vec=[1,2,3,4,5,6]
array_reshape(vec, 2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
mat = np.array([[1.2,"s",3],
               [4,5,6],
               [7,8,9]])
mat.dtype
mat

array([['1.2', 's', '3'],
       ['4', '5', '6'],
       ['7', '8', '9']], dtype='<U32')

In [15]:
mat = np.array([[1.2,"5",3],
               [4,5,6],
               [7,8,9]])

fmat = mat.astype(np.float64)
print(fmat.dtype)
fmat


float64


array([[1.2, 5. , 3. ],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ]])

In [2]:
x= np.array([1,2,3])
x.shape

(3,)

In [16]:
def  convert_dtype(arr, dtype):
    try:
        arr=np.asarray(arr)
        return arr.astype(dtype)
    
    except TypeError as e:
        raise TypeError(f"invalid target data type:{dtype}") from e
    
    except ValueError as e:
        raise ValueError(f"can not convert value to {dtype}") from e

In [4]:
def check_dtype(arr, dtype):
  
    if not isinstance(arr, np.ndarray):
            raise TypeError  ("input must be a numpy array")
        
    dtype = np.dtype(dtype)
    return arr.dtype == dtype          

In [6]:
mat = np.full((3,4),5)
mat

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [9]:
def init_array(shape, value=0):
    return np.full(shape, value)

In [13]:
ones = init_array((3,4),10)
ones

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [6]:
def init_weights(n_feature, method = "zeros", seed = None):
    if not isinstance(n_feature, int):
        raise TypeError(f"{n_feature} must be an integer")
    
    if n_feature<=0:
        raise TypeError(f"{n_feature} must be greater than zero")
    if method=="zeros":
        return np.zeros(n_feature)
    if method=="random":
        if seed is not None:
            np.random.seed(seed)
        return np.random.random(n_feature)* 0.01
    
    raise ValueError(f"unsupported method type {method}")        
    

In [5]:
init_weights(4,"random",42)

array([0.0037454 , 0.00950714, 0.00731994, 0.00598658])

In [10]:
np.random.randint(0, 11,(5,5))

array([[ 1,  2,  0,  5,  3],
       [ 4,  5, 10,  9,  9],
       [ 8, 10,  1, 10,  3],
       [ 8,  0,  0,  4,  3],
       [ 2,  5,  8,  1,  6]])

In [11]:
a= ["osama","basel",'amira']
np.random.choice(a, size=(3,5))

array([['amira', 'basel', 'amira', 'amira', 'amira'],
       ['osama', 'amira', 'amira', 'osama', 'basel'],
       ['amira', 'amira', 'amira', 'osama', 'basel']], dtype='<U5')

In [15]:
mat1 = np.ones((3,4))
mat2 = np.zeros((3,4))
 
np.savez("file_da.npz", ones_mat=mat1, zeros_mat=mat2) 


In [18]:
with np.load("file_da.npz") as file:
    mat1 = file["ones_mat"]
    mat2 = file["zeros_mat"]

mat2    

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
m1 = np.array([[1,2,3],
              [0,0,0]])

m2 = np.array([[4,5,6],
              [1,1,1]])

In [25]:
nem_mat = np.hstack((m1,m2))
nem_mat

array([[1, 2, 3, 4, 5, 6],
       [0, 0, 0, 1, 1, 1]])

In [26]:
v = np.array([1,2,3,4,5,0])
np.all(v>=1)

np.False_

In [27]:
np.any(v>=1)

np.True_

In [29]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([2,3,0,5,3])

np.isclose(v1,v2, atol=1)

array([ True,  True, False,  True, False])

In [30]:
np.allclose(v1,v2, atol=1)

False

In [ ]:
v= np.array([2,4,3,4,10])
condition = v>4
print(condition)


[False False False False  True]


In [33]:
v= np.array([2,4,3,4,10])
condition = v>=4
v[condition]=-1
print(v)

[ 2 -1  3 -1 -1]


In [ ]:
v= np.array([2,4,3,4,10])
condition = v>=4
new_arr = np.where(condition, -1, v)
new_arr

array([ 2, -1,  3, -1, -1])

In [35]:
v1 = np.array([1,4,3])
c=2
summation = v1+c
multiplication=v1*c
print(summation)
print(multiplication)

[3 6 5]
[2 8 6]
